/**
 * Regenerate samples/samples.tex — a printable EBNF reference that pairs each
 * example grammar with its rendered TikZ diagram(s). Generated from the same
 * pipeline the app uses, so the diagrams never drift from the engine.
 *
 *   npx vite-node scripts/gen-samples-tex.ts   (or: npm run samples:tex)
 *
 * Compile to samples/samples.pdf with `npm run samples:pdf` (pdflatex via
 * latexmk). Do not edit samples.tex by hand — it is overwritten on every run.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { generate } from "../src/pipeline";
import { SAMPLE_GRAMMAR } from "../src/ui/sample";

const outDir = resolve(dirname(fileURLToPath(import.meta.url)), "../samples");
mkdirSync(outDir, { recursive: true });

/**
 * Curated showcase: one example per notable EBNF construct, plus a small
 * multi-rule grammar. ASCII-only so the document compiles under pdflatex.
 */
const examples: Array<{ title: string; grammar: string }> = [
  {
    title: "Concatenation with a repeated separator",
    grammar: `expression = term, { ("+" | "-"), term };`,
  },
  {
    title: "Alternation and grouping",
    grammar: `factor = number | "(", expression, ")";`,
  },
  {
    title: "Optional and one-or-more",
    grammar: `signed number = [ "+" | "-" ], digit, { digit };`,
  },
  {
    title: "Repetition factor",
    grammar: `triplet = 3 * digit;`,
  },
  {
    title: "Special sequence",
    grammar: `token = ? implementation-defined ? ;`,
  },
  {
    title: "Exception",
    grammar: `consonant = letter - vowel ;`,
  },
  {
    title: "A complete grammar (multiple rules)",
    grammar: SAMPLE_GRAMMAR,
  },
  {
    title: "EBNF described in EBNF",
    grammar: `(* EBNF described in EBNF (after ISO/IEC 14977) *)

grammar = { rule };

rule = identifier, "=", definitions list, ";";

definitions list = single definition, { "|", single definition };

single definition = term, { ",", term };

term = factor, [ "-", factor ];

factor = [ integer, "*" ], primary;

primary = optional sequence
        | repeated sequence
        | grouped sequence
        | identifier
        | terminal string
        | special sequence;

optional sequence = "[", definitions list, "]";

repeated sequence = "{", definitions list, "}";

grouped sequence = "(", definitions list, ")";

terminal string = '"', character, { character }, '"'
                | "'", character, { character }, "'";

special sequence = "?", { character }, "?";

identifier = letter, { letter | digit | " " };

integer = digit, { digit };
`,
  },
];

/** Escape a rule name for use in LaTeX running text (headings). */
function latexText(s: string): string {
  return s.replace(/([\\&%$#_{}~^])/g, "\\$1");
}

const PREAMBLE = `\\documentclass{article}
\\usepackage{tikz}
\\usepackage{xcolor}
\\usepackage{adjustbox}

\\title{Syntax Diagram Generator --- EBNF examples}
\\date{}

\\begin{document}
\\maketitle

\\noindent Each example below pairs an EBNF grammar (ISO/IEC 14977) with the
railroad diagram the generator produces for every one of its rules. The diagrams
are the tool's own TikZ output.
`;

const parts: string[] = [
  "% Generated by scripts/gen-samples-tex.ts — do not edit by hand.",
  "% Regenerate with: npm run samples:tex",
  PREAMBLE,
];

for (const { title, grammar } of examples) {
  const diagrams = generate(grammar, "ebnf");
  parts.push(`\\section{${latexText(title)}}`);
  parts.push("\\begin{verbatim}");
  parts.push(grammar.trim());
  parts.push("\\end{verbatim}");
  for (const d of diagrams) {
    parts.push("");
    parts.push(`\\paragraph{${latexText(d.name)}}\\mbox{}\\\\[2pt]`);
    parts.push(d.tikz);
  }
  parts.push("");
}

parts.push("\\end{document}");

const outPath = resolve(outDir, "samples.tex");
writeFileSync(outPath, parts.join("\n") + "\n");
console.log(`wrote samples/samples.tex (${examples.length} examples)`);
